Document: boost-statechart-viewer
Title: Debian boost-statechart-viewer Manual
Author: <insert document author here>
Abstract: This manual describes what boost-statechart-viewer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/boost-statechart-viewer/boost-statechart-viewer.sgml.gz

Format: postscript
Files: /usr/share/doc/boost-statechart-viewer/boost-statechart-viewer.ps.gz

Format: text
Files: /usr/share/doc/boost-statechart-viewer/boost-statechart-viewer.text.gz

Format: HTML
Index: /usr/share/doc/boost-statechart-viewer/html/index.html
Files: /usr/share/doc/boost-statechart-viewer/html/*.html
